insert into public.products (
  id,
  name,
  description,
  weight_grams,
  price_cents,
  active,
  sort_order
)
values
  ('aparador-de-livro-dragao', 'Aparador de livro - Dragão', null, 150, 4000, true, 0),
  ('caixa-de-dados-p', 'Caixa de Dados P', null, 74, 3000, true, 1),
  ('caixa-polaroid', 'Caixa Polaroid', null, 100, 5000, true, 2),
  ('chaveiro-calendario', 'Chaveiro Calendário', null, 12, 1500, true, 3),
  ('chaveiro-cartinha', 'Chaveiro Cartinha', null, 16, 1000, true, 4),
  ('chaveiro-yumi', 'Chaveiro Yumi', null, 15, 1000, true, 5),
  ('clicker-capivara', 'Clicker Capivara', null, null, null, true, 6),
  ('enfeite-home-m', 'Enfeite Home - M', null, 72, 2000, true, 7),
  ('figure-balrog', 'Figure Balrog', null, null, null, true, 8),
  ('figure-frieren', 'Figure Frieren', null, null, null, true, 9),
  ('figure-legolas-ogro', 'Figure Legolas Ogro', null, null, null, true, 10),
  ('fruta-one-piece', 'Fruta One Piece', null, 85, 4000, true, 11),
  ('jogo-equilibrio', 'Jogo de Equilíbrio', 'Jogo de equilíbrio com árvore, caixa e conjunto de peças temáticas à escolha.', null, null, true, 12),
  ('kit-monster-v1', 'Kit Monster V1', null, 157, 5000, true, 13),
  ('kit-porta-copos-flor', 'Kit Porta Copos Flor', null, 257, 10000, true, 14),
  ('mecanismo-clicker', 'Mecanismo Clicker', null, 3, 150, true, 15),
  ('kit-mini-prendedores-10', 'Kit de Mini Prendedores - 10 unidades', 'Kit com dez mini prendedores para fechar pacotes e embalagens abertas.', null, null, true, 16),
  ('lagarto-tom', 'Lagarto Tom', null, 45, 2000, true, 17),
  ('marca-pagina-gatinho', 'Marca-página Gatinho', null, 2, 500, true, 18),
  ('organizador-magic', 'Organizador Magic', null, 107, 3500, true, 19),
  ('porta-celular-stars', 'Porta Celular STARS', null, 121, 8000, true, 20),
  ('porta-copo-gatinho-batman', 'Porta copo - Gatinho Batman', null, 25, 1000, true, 21),
  ('porta-copos-costela-de-adao', 'Porta Copos - Costela de Adão', null, 170, 6000, true, 22),
  ('porta-copos-planta', 'Porta Copos - Planta', null, 206, 7000, true, 23),
  ('porta-cotonete', 'Porta Cotonete', null, 97, 4000, true, 24),
  ('porta-guardanapo-costela-de-adao', 'Porta Guardanapo - Costela de Adão', null, 73, 2500, true, 25),
  ('porta-incenso-gato', 'Porta Incenso Gato', null, 51, 2500, true, 26),
  ('porta-joias', 'Porta Jóias', null, 392, 13000, true, 27),
  ('porta-maquiagem', 'Porta Maquiagem', null, 580, 16000, true, 28),
  ('kit-porta-polaroid-coracao-5', 'Kit Porta Polaroid Coração - 5 unidades', 'Kit com cinco suportes pequenos em formato de coração para fotos Polaroid.', 10, 1000, true, 29),
  ('kit-porta-polaroid-coracao-10', 'Kit Porta Polaroid Coração - 10 unidades', 'Kit com dez suportes pequenos em formato de coração para fotos Polaroid.', 20, 2000, true, 30),
  ('porta-remedios-umbrella', 'Porta Remédios Umbrella', null, 20, 1000, true, 31),
  ('separador-de-livro-dragao', 'Separador de livro - Dragão', null, 212, 5500, true, 32),
  ('suporte-para-2-controles', 'Suporte para 2 controles', 'Suporte para dois controles com encaixes à escolha entre PS3, PS4 e PS5.', 213, 6000, true, 33),
  ('suporte-para-3-controles', 'Suporte para 3 controles', 'Suporte para três controles com encaixes à escolha entre PS3, PS4 e PS5.', 318, 8500, true, 34),
  ('suporte-controle-gengar', 'Suporte Controle Gengar', null, null, null, true, 35),
  ('suporte-de-chave-mario', 'Suporte de chave - Mario', null, 230, 7500, true, 36),
  ('suporte-oculos-gatinho', 'Suporte de óculos - Gatinho', null, null, null, true, 37),
  ('suporte-livro-darth-vader', 'Suporte livro Darth Vader', null, 123.8, 4500, true, 38),
  ('tampa-caneca-chapeu-seletor', 'Tampa Caneca Chapéu Seletor', null, null, null, true, 39),
  ('trono-de-ferro', 'Trono de Ferro', null, 33, 2000, true, 40),
  ('vaso', 'Vaso', null, 210, 6000, true, 41),
  ('caixa-uno', 'Caixa Uno', null, 91, 2500, true, 42),
  ('quadro-reforco-infantil', 'Quadro Reforço Infantil', null, 210, 5000, true, 43)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  weight_grams = excluded.weight_grams,
  price_cents = excluded.price_cents,
  active = excluded.active,
  sort_order = excluded.sort_order;
